### ISSUE TITLE
Parser - Binary Expression Tokens

### ISSUE THREAD

**Issue by CalebLItalien** [UnionCompilerDesign/compiler_core#101]
### Details
Add the rest of the tokens required for parsing binary expressions according to #97. 

### Issue Type
- [X] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Refactoring
- [ ] Other:

### Requirements
- The complete list of tokens established as well as correct parsing of binary expressions defined in #57, as well as unit testing for all new tokens.

### Notes

**Comment by Dalyj24** [comment]
This is unnecessary as binary expressions now parse correctly without extra tokens.
