### ISSUE TITLE
Module - Multithreading  (IF TIME - LEAST PRIORITY) 🝰

### ISSUE THREAD

**Issue by kjwelch** [UnionCompilerDesign/compiler_core#147]
### Details
Currently, the compiler creates `modElements` one by one from `entry_points`. 

Using `thread_pool_executer.rs`, multi thread this process to concurrently create `modElements`. 

### Issue Type
- [X] Feature
- [ ] Bugfix
- [ ] Documentation
- [X] Refactoring
- [ ] Other:

### Requirements
- Distribute work among Threads: Slice the content of your source file based on the entry_points and distribute these slices to different threads in the pool. Each thread will process its slice to generate a ModElement.
- Collect Results: Once all threads have completed their work, the results (i.e., the ModElement instances) must be collected and turned into a Module.
- Most of this will be done in `compiler.rs` under the main driver, `compile`

### Notes

Make sure to include proper documentation and testing.

**Comment by CalebLItalien** [comment]
You'll want to be careful with how you combine sts's. Each top level expression is part of a global scope in a file, so your stitching funcionality (at the end of each thread's execution) inside the sts struct will need to account for this. Similarly, ast combinations across threading have to be careful and this is currently done in ast_stitch, though ast_stitch needs to be moved inside the ast struct and needs enhanced functionality.
