### ISSUE TITLE
STS: backend tag addition

### ISSUE THREAD

**Issue by Dalyj24** [UnionCompilerDesign/compiler_core#189]
### Details
A small change must be made to the STS in order to support variable assignment and initialization in backend. A field has to be added which will hold the allocation tags of variables for use in IR generation.
### Issue Type
- [x] Feature
- [ ] Bugfix
- [ ] Documentation
- [x] Refactoring
- [ ] Other:

### Notes

**Comment by CalebLItalien** [comment]
@Dalyj24 was this issue closed?

**Comment by Dalyj24** [comment]
Issue was not necessary in light of other fixes
