### ISSUE TITLE
Opaque SyntaxElement - Function Declaration

### ISSUE THREAD

**Issue by CalebLItalien** [UnionCompilerDesign/compiler_core#58]
### Details
Update the analysis of function declarations within the `SemAnalysis` to the new opaque SyntaxElement API. Begin with the foundation provided by the commented-out code, and ensure we can accurately distinguish between well-formed and ill-formed function declarations.

### Issue Type
- [X] Feature
- [ ] Bugfix
- [ ] Documentation
- [X] Refactoring
- [ ] Other:

### Requirements
- Integration with the new `SyntaxElement` API
- Recognition of well-formed functions
- Recognition of ill-formed functions
- Comprehensive Testing

### Notes

**Comment by CalebLItalien** [comment]
@tbreimer14 - What checks do you plan on using to test whether or not a function is well-formed?

**Comment by tbreimer14** [comment]
@CalebLItalien 

I think it would be important to test that 

1. The function name isn't already defined in the scope
2. Parameter and return types declared in the signature correspond to their use in the function body
3. There is always a reachable return statement if the function is defined to return something
4. Probably need to deal with capture somehow if we're doing that
5. Check if it conforms to our overloading rules (whatever those are)
