### ISSUE TITLE
Unary vs binary minus

### ISSUE THREAD

**Issue by Dalyj24** [UnionCompilerDesign/compiler_core#93]
### Details
Right now there's only one minus token and the parser can't distinguish between a unary and a binary - sign.
This means that something like "5 - 1" is detected right, but the number "-5" is not.

### Issue Type
- [ ] Feature
- [x] Bugfix
- [ ] Documentation
- [ ] Refactoring
- [ ] Other:

### Requirements
Probably add a new token so that the parser can know the difference, and then edit the parser to parse a unary - correctly.

### Notes

**Comment by CalebLItalien** [comment]
@Dalyj24 What kind of token would you consider adding?

**Comment by kjwelch** [comment]
![Image](https://github.com/UnionCompilerDesign/compiler_core/assets/123904001/31376770-4ae6-44b7-aa49-0a0b42e32150)

**Comment by kjwelch** [comment]
Here is my approach to unary vs binary operators worked out in pseudocode for '-'. In dealing with subtraction vs negative tokens for '-', these other binary cases (-= and --) should be handled as well (To cover all tokens with '-'). Currently, tokens do not exist for the following binary (-=,+=,*=,/=) and unary (--, ++) operators. Similar logic should also extend to  +, +=, and ++. 

This may or may not be helpful for issue #57 @Dalyj24 :)
